apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # Sets as default
provisioner: kubernetes.io/no-provisioner  # For local storage
volumeBindingMode: WaitForFirstConsumer  # Ensures pod scheduling works with local volumes
reclaimPolicy: Retain  # Keeps data when PVC is deleted
allowVolumeExpansion: true  # Local volumes typically can't expand
