apiVersion: v1
kind: Secret
metadata:
  name: ghcr-io-secret
  namespace: t3-cloneathon
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "YOUR_GITHUB_USERNAME",
          "password": "YOUR_GITHUB_TOKEN"
        }
      }
    }
---
# To create this secret properly, run:
# kubectl create secret docker-registry ghcr-io-secret \
#   --docker-server=ghcr.io \
#   --docker-username=YOUR_GITHUB_USERNAME \
#   --docker-password=YOUR_GITHUB_TOKEN \
#   --namespace=t3-cloneathon

