apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: t3-cloneathon
  annotations:
    description: "Application secrets - all values must be base64 encoded"
type: Opaque
data:
  POSTGRES_PASSWORD: YOUR_POSTGRES_PASSWORD_BASE64  # Replace with your postgres password (base64 encoded)
  REDIS_PASSWORD: YOUR_REDIS_PASSWORD_BASE64  # Replace with your Redis password (base64 encoded, leave empty if no password)
  BETTER_AUTH_SECRET: YOUR_BETTER_AUTH_SECRET_BASE64  # Replace with your Better Auth secret key (base64 encoded)
  DISCORD_CLIENT_ID: YOUR_DISCORD_CLIENT_ID_BASE64  # Replace with your Discord client ID (base64 encoded)
  DISCORD_CLIENT_SECRET: YOUR_DISCORD_CLIENT_SECRET_BASE64  # Replace with your Discord client secret (base64 encoded)
