apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: t3-cloneathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379

        # 1. Inject the password from the secret
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_PASSWORD

        # 2. Wrap in sh -c so that $REDIS_PASSWORD is expanded
        command:
        - sh
        - -c
        - |
          exec redis-server \
            --appendonly no \
            --requirepass "$REDIS_PASSWORD"

        volumeMounts:
        - name: redis-storage
          mountPath: /data

        # 3. Probes must also use a shell to expand the env var
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - redis-cli -a "$REDIS_PASSWORD" ping
          initialDelaySeconds: 30
          timeoutSeconds: 5

        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - redis-cli -a "$REDIS_PASSWORD" ping
          initialDelaySeconds: 5
          timeoutSeconds: 1

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
